services:
  - type: web
    name: balanzen-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: balanzen-db
          property: connectionString

databases:
  - name: balanzen-db
    databaseName: balanzen
    user: balanzen
    plan: free
